server:
  port: 8001
spring:
  application:
    name: goods-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.197.145:8848
        group: yi5an
      config:
        server-addr: 47.92.197.145:8848
        group: yi5an
        file-extension: properties

seata:
  application-id: goods-service
  enabled: true
  tx-service-group: test_save_order_group
  service:
    vgroup-mapping: <test_save_order_group, default>
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 47.92.197.145:8848
