server:
  port: 8003
spring:
  application:
    name: shopcart-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.197.145:8848
        group: yi5an
      config:
        server-addr: 47.92.197.145:8848
        group: yi5an
        file-extension: properties